basePath: /
definitions:
  domain.GenderType:
    enum:
    - MALE
    - FEMALE
    type: string
    x-enum-varnames:
    - MALE
    - FEMALE
  domain.Response:
    properties:
      data: {}
      error: {}
      message:
        type: string
      success:
        type: boolean
    type: object
  payload.UpdateUserDTO:
    properties:
      address:
        type: string
      dob:
        type: string
      firstName:
        type: string
      gender:
        $ref: '#/definitions/domain.GenderType'
      lastName:
        type: string
      phone:
        minLength: 10
        type: string
      prefix:
        type: string
    required:
    - address
    - dob
    - firstName
    - gender
    - lastName
    - prefix
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server celler server.
  title: CPE241 Project Backend API
  version: "1.0"
paths:
  /api/healthcheck:
    get:
      description: Health checking for the service
      operationId: HealthCheckHandler
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Response'
      summary: Health Check
  /api/user/:
    patch:
      consumes:
      - application/json
      description: Update user information
      parameters:
      - description: Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/payload.UpdateUserDTO'
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Update user information
      tags:
      - user
schemes:
- https
- http
swagger: "2.0"
